version: "2"
services:

  db:
    image: postgres
    ports:
      - "5433:5432" 
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: /Pass@098/
      POSTGRES_USER: dbmanager
      POSTGRES_DB: hoteldb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgres-data
    healthcheck:
      test: [ "CMD", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 20s
      retries: 10
  app:
    image:  hotelroom
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: dbmanager
      DB_URL: jdbc:postgresql://db:5432/hoteldb
      DB_PASSWORD: /Pass@098/
      HOST_NAME: localhost
    networks: 
      - my-network  
    depends_on:
      - db
        
    command:  ["sh", "-c", "java -jar /app/app.jar hotel.Main"]

    # command: ["sh", "-c", "ls -la / && cd app && ls -al"]
  
networks:
  my-network:
    driver: bridge

volumes:
  db-data: