services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgres-data
    healthcheck:
      test: ["CMD", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 10
  app:
    image: hotelroom
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - my-network
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "  sleep 1;  java -Djava.awt.headless=false -jar /app/app.jar --dbUser ${DB_USER} --dbHost ${DB_URL}  --dbPassword ${DB_PASSWORD}",
      ]

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
