version: '3.9'

services:

  db:
    image: postgres
    ports:
      - "5433:5432" 
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: /Pass@098/
      POSTGRES_USER: dbmanager
      POSTGRES_DB: hoteldb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgres-data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
      
  app:
    image:  hotelroom
    networks: 
      - my-network  
    depends_on:
      db:
        condition: service_healthy

networks:
  my-network:
    driver: bridge

volumes:
  db-data: