name: Java CI with Maven in Linux

on:
  push: 
    branches: 
      - main
      - github_action
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17]
    
    name: Build with Java ${{ matrix.java }}
    steps:

    - uses: actions/checkout@v4

    - name: Setup up JDK ${{ matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    
    # Build with Maven
    - name: Build with Maven ${{ matrix.java }}
      run: > 
        mvn -f ./pom.xml 
        clean verify
        clean verify
        surefire-report:report-only site:site -DgenerateReports=false

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      with:
        name: surefire-report-jdk-${{ matrix.java }}
        path: '**/target/site'