name: Java CI with Maven in Linux

on:
  push: 
    branches: 
      - main
      - feat_e2e
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        additional-maven-args: 
          - "-Pjacoco -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report -DpullRequest=${{ github.event.pull_request.number }}"

    name: Build with Java ${{ matrix.java }}
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Generate JUnit Report
        run: >
          xvfb-run mvn -f ./pom.xml
          clean verify -Pjacoco ${{ matrix.additional-maven-args }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ always() }}

#      - name: Build with Maven ${{ matrix.java }}
#        run: xvfb-run mvn -f ./pom.xml clean verify

      - name: Archive JUnit Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: jacoco-report-jdk-${{ matrix.java }}
          path: '**/target/site'

#      - name: Build with Maven
#        run: xvfb-run mvn verify
#        working-directory: hotel

#      - name: Setup JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11

      - name: SonarCloud and Build with Maven
        run: >
          xvfb-run mvn -f ./pom.xml verify -Pjacoco sonar:sonar
          -Dsonar.organization=unifi-resilience
          -Dsonar.host.url=https://sonarcloud.io
		  -Dsonar.projectKey=com.hotels.app:rooms \
		  -Dsonar.projectName="hotelroom" \
		  -Dsonar.branch.name=main
#        working-directory: hotel
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
