name: Java CI with Maven in Linux

on:
  push: 
    branches: 
      - main
      - github_action
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17' # Corrected to use '17' instead of '1.17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
            
      # Build with Maven
      - name: Build with Maven
        run: mvn -f ./pom.xml clean verify
